Add icons and Update UI
flackonInc/docupilot-airtable-block pull request #8
Opened 2021-07-09 07:48 UTC by ravalikab

- Add new svg icons
- Update UI for successful document creation

2021-07-09 14:23 UTC, tiholic requested changes

2021-07-09 14:23 UTC, tiholic commented on frontend/images.tsx
> +const googleDocsIcon = <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
@ravalikab can we re-arrange them so that all doc icons are together? - after png and before master logo's

2021-07-09 14:23 UTC, tiholic commented on frontend/common.tsx
> +                  width: '100px',
Can we avoid configuring fixed width? Something like `calc(100vw - 150px)` would auto adjust based on the block width.

2021-07-09 14:23 UTC, tiholic commented on frontend/common.tsx
> +            //  ignoring this as Link needs a mandatory child, against AirTable docs
Improvise this message:

"ignoring as Link needs mandatory child, but Airtable link with icon inserts a child element"

2021-07-13 13:04 UTC, ravalikab commented on frontend/images.tsx
> +const googleDocsIcon = <svg width="32" height="32" viewBox="0 0 32 32" fill="none" xmlns="http://www.w3.org/2000/svg">
Re-arranged svg icons.
Commit : 9ae77f94fcf5ad70351220b538ae2189c2537497

2021-07-13 13:09 UTC, ravalikab commented on frontend/common.tsx
> +            //  ignoring this as Link needs a mandatory child, against AirTable docs
Changed the comment.
Commit : cf16e60a6328f252fb3ae49d29dc071ebe5ec375

2021-07-13 13:27 UTC, ravalikab commented on frontend/common.tsx
> +                  width: '100px',
Changed width to calc(100vw - 250px)
Commit : a68feca7aece16b31d6a03132838ee10458205eb

2021-07-29 18:24 UTC, merged